// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcom;
import com.roo1try1.AgentTelcomPK;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentTelcom_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager AgentTelcom.entityManager;
    
    public static final List<String> AgentTelcom.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager AgentTelcom.entityManager() {
        EntityManager em = new AgentTelcom().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AgentTelcom.countAgentTelcoms() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AgentTelcom o", Long.class).getSingleResult();
    }
    
    public static List<AgentTelcom> AgentTelcom.findAllAgentTelcoms() {
        return entityManager().createQuery("SELECT o FROM AgentTelcom o", AgentTelcom.class).getResultList();
    }
    
    public static List<AgentTelcom> AgentTelcom.findAllAgentTelcoms(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AgentTelcom o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AgentTelcom.class).getResultList();
    }
    
    public static AgentTelcom AgentTelcom.findAgentTelcom(AgentTelcomPK id) {
        if (id == null) return null;
        return entityManager().find(AgentTelcom.class, id);
    }
    
    public static List<AgentTelcom> AgentTelcom.findAgentTelcomEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AgentTelcom o", AgentTelcom.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<AgentTelcom> AgentTelcom.findAgentTelcomEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AgentTelcom o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AgentTelcom.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AgentTelcom.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AgentTelcom.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AgentTelcom attached = AgentTelcom.findAgentTelcom(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AgentTelcom.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AgentTelcom.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AgentTelcom AgentTelcom.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AgentTelcom merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
