// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.Agent;
import com.roo1try1.AgentTelcom;
import com.roo1try1.Telcom;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect AgentTelcom_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "agid", referencedColumnName = "agid", insertable = false, updatable = false)
    private Agent AgentTelcom.agid;
    
    @ManyToOne
    @JoinColumn(name = "id_telcom", referencedColumnName = "id", insertable = false, updatable = false)
    private Telcom AgentTelcom.idTelcom;
    
    public Agent AgentTelcom.getAgid() {
        return agid;
    }
    
    public void AgentTelcom.setAgid(Agent agid) {
        this.agid = agid;
    }
    
    public Telcom AgentTelcom.getIdTelcom() {
        return idTelcom;
    }
    
    public void AgentTelcom.setIdTelcom(Telcom idTelcom) {
        this.idTelcom = idTelcom;
    }
    
}
