// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcomPK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect AgentTelcomPK_Roo_Json {
    
    public String AgentTelcomPK.toJson() {
        return new JSONSerializer()
        .exclude("*.class").serialize(this);
    }
    
    public String AgentTelcomPK.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").serialize(this);
    }
    
    public static AgentTelcomPK AgentTelcomPK.fromJsonToAgentTelcomPK(String json) {
        return new JSONDeserializer<AgentTelcomPK>()
        .use(null, AgentTelcomPK.class).deserialize(json);
    }
    
    public static String AgentTelcomPK.toJsonArray(Collection<AgentTelcomPK> collection) {
        return new JSONSerializer()
        .exclude("*.class").serialize(collection);
    }
    
    public static String AgentTelcomPK.toJsonArray(Collection<AgentTelcomPK> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<AgentTelcomPK> AgentTelcomPK.fromJsonArrayToAgentTelcomPKs(String json) {
        return new JSONDeserializer<List<AgentTelcomPK>>()
        .use("values", AgentTelcomPK.class).deserialize(json);
    }
    
}
