// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.Agent;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Agent_Roo_Jpa_Entity {
    
    declare @type: Agent: @Entity;
    
    declare @type: Agent: @Table(schema = "socker", name = "agent");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "agid", columnDefinition = "int8")
    private Long Agent.agid;
    
    public Long Agent.getAgid() {
        return this.agid;
    }
    
    public void Agent.setAgid(Long id) {
        this.agid = id;
    }
    
}
