// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcom;
import com.roo1try1.AgentTelcomPK;
import com.roo1try1.AgentTelcomService;
import java.util.List;

privileged aspect AgentTelcomService_Roo_Service {
    
    public abstract long AgentTelcomService.countAllAgentTelcoms();    
    public abstract void AgentTelcomService.deleteAgentTelcom(AgentTelcom agentTelcom);    
    public abstract AgentTelcom AgentTelcomService.findAgentTelcom(AgentTelcomPK id);    
    public abstract List<AgentTelcom> AgentTelcomService.findAllAgentTelcoms();    
    public abstract List<AgentTelcom> AgentTelcomService.findAgentTelcomEntries(int firstResult, int maxResults);    
    public abstract void AgentTelcomService.saveAgentTelcom(AgentTelcom agentTelcom);    
    public abstract AgentTelcom AgentTelcomService.updateAgentTelcom(AgentTelcom agentTelcom);    
}
