// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcomPK;
import java.io.Serializable;

privileged aspect AgentTelcomPK_Roo_Serializable {
    
    declare parents: AgentTelcomPK implements Serializable;
    
    private static final long AgentTelcomPK.serialVersionUID = 1L;
    
}
