// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.Agent;
import com.roo1try1.AgentServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentServiceImpl_Roo_Service {
    
    declare @type: AgentServiceImpl: @Service;
    
    declare @type: AgentServiceImpl: @Transactional;
    
    public long AgentServiceImpl.countAllAgents() {
        return Agent.countAgents();
    }
    
    public void AgentServiceImpl.deleteAgent(Agent agent) {
        agent.remove();
    }
    
    public Agent AgentServiceImpl.findAgent(Long id) {
        return Agent.findAgent(id);
    }
    
    public List<Agent> AgentServiceImpl.findAllAgents() {
        return Agent.findAllAgents();
    }
    
    public List<Agent> AgentServiceImpl.findAgentEntries(int firstResult, int maxResults) {
        return Agent.findAgentEntries(firstResult, maxResults);
    }
    
    public void AgentServiceImpl.saveAgent(Agent agent) {
        agent.persist();
    }
    
    public Agent AgentServiceImpl.updateAgent(Agent agent) {
        return agent.merge();
    }
    
}
