// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcom;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AgentTelcom_Roo_Configurable {
    
    declare @type: AgentTelcom: @Configurable;
    
}
