// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcom;
import com.roo1try1.AgentTelcomPK;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect AgentTelcom_Roo_Jpa_Entity {
    
    declare @type: AgentTelcom: @Entity;
    
    declare @type: AgentTelcom: @Table(schema = "socker", name = "agent_telcom");
    
    @EmbeddedId
    private AgentTelcomPK AgentTelcom.id;
    
    public AgentTelcomPK AgentTelcom.getId() {
        return this.id;
    }
    
    public void AgentTelcom.setId(AgentTelcomPK id) {
        this.id = id;
    }
    
}
