// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.Agent;
import com.roo1try1.AgentTelcom;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect Agent_Roo_DbManaged {
    
    @OneToMany(mappedBy = "agid")
    private Set<AgentTelcom> Agent.agentTelcoms;
    
    @Column(name = "agtype", columnDefinition = "int4")
    @NotNull
    private Integer Agent.agtype;
    
    @Column(name = "name", columnDefinition = "text")
    @NotNull
    private String Agent.name;
    
    @Column(name = "agstatus", columnDefinition = "int4")
    private Integer Agent.agstatus;
    
    public Set<AgentTelcom> Agent.getAgentTelcoms() {
        return agentTelcoms;
    }
    
    public void Agent.setAgentTelcoms(Set<AgentTelcom> agentTelcoms) {
        this.agentTelcoms = agentTelcoms;
    }
    
    public Integer Agent.getAgtype() {
        return agtype;
    }
    
    public void Agent.setAgtype(Integer agtype) {
        this.agtype = agtype;
    }
    
    public String Agent.getName() {
        return name;
    }
    
    public void Agent.setName(String name) {
        this.name = name;
    }
    
    public Integer Agent.getAgstatus() {
        return agstatus;
    }
    
    public void Agent.setAgstatus(Integer agstatus) {
        this.agstatus = agstatus;
    }
    
}
