// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo1try1;

import com.roo1try1.AgentTelcom;
import com.roo1try1.AgentTelcomPK;
import com.roo1try1.AgentTelcomServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentTelcomServiceImpl_Roo_Service {
    
    declare @type: AgentTelcomServiceImpl: @Service;
    
    declare @type: AgentTelcomServiceImpl: @Transactional;
    
    public long AgentTelcomServiceImpl.countAllAgentTelcoms() {
        return AgentTelcom.countAgentTelcoms();
    }
    
    public void AgentTelcomServiceImpl.deleteAgentTelcom(AgentTelcom agentTelcom) {
        agentTelcom.remove();
    }
    
    public AgentTelcom AgentTelcomServiceImpl.findAgentTelcom(AgentTelcomPK id) {
        return AgentTelcom.findAgentTelcom(id);
    }
    
    public List<AgentTelcom> AgentTelcomServiceImpl.findAllAgentTelcoms() {
        return AgentTelcom.findAllAgentTelcoms();
    }
    
    public List<AgentTelcom> AgentTelcomServiceImpl.findAgentTelcomEntries(int firstResult, int maxResults) {
        return AgentTelcom.findAgentTelcomEntries(firstResult, maxResults);
    }
    
    public void AgentTelcomServiceImpl.saveAgentTelcom(AgentTelcom agentTelcom) {
        agentTelcom.persist();
    }
    
    public AgentTelcom AgentTelcomServiceImpl.updateAgentTelcom(AgentTelcom agentTelcom) {
        return agentTelcom.merge();
    }
    
}
